# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Security
    app.authenticator:
        class: App\Security\Authenticator
        public: true

    App\Security\Authenticator: "@app.authenticator"

    # Command
    App\Command\CreateAuthorCommand:
        class: 'App\Command\CreateAuthorCommand'
        tags: [console.command]
        arguments: 
            $apiUserEmail: '%env(API_USER_EMAIL)%'
            $apiUserPassword: '%env(API_USER_PASSWORD)%'

    # Form
    app.login-form-type:
        class: App\Form\LoginFormType
        public: true

    app.book-type.form:
        class: App\Form\BookFormType
        public: true

    # Application service
    app.security-service:
        class: App\Service\SecurityService
        public: true
        arguments: 
            $apiBaseUrl: '%env(API_BASE_URL)%'

    App\Service\SecurityServiceInterface: "@app.security-service"

    # Repository  
    App\Infrastructure\Repository\:
        resource: "../src/Infrastructure/Repository"
        arguments:
            $apiBaseUrl: '%env(API_BASE_URL)%'

    App\Domain\Repository\AuthorRepositoryInterface: '@App\Infrastructure\Repository\AuthorRepository'
    App\Domain\Repository\BookRepositoryInterface: '@App\Infrastructure\Repository\BookRepository'

    #Utils

    ## Api client
    app.api-client:
        class: 'App\Utils\ApiClient\ApiClient'

    App\Utils\ApiClient\ApiClientInterface: "@app.api-client"
    
    ## Session
    app.http-session:
        class: App\Utils\Session\HttpSession

    app.console-session:
        class: App\Utils\Session\ConsoleSession

    app.session-factory:
        class: App\Utils\Session\SessionFactory

    App\Utils\Session\SessionInterface: '@app.http-session'

    ## Filter
    app.filter-options:
        class: App\Utils\Filter\FilterOptions
        public: true

    App\Utils\Filter\FilterOptionsInterface: "@app.filter-options"

    #Transformer
    App\Transformer\:
        resource: "../src/Transformer"

    App\Transformer\UserTransformerInterface: '@App\Transformer\UserTransformer'
